version: '3'

services:
  redteam:
    build: .
    container_name: redteam-engine
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      #- ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    tty: true